# 15.2 Exception

## 15.2.1 Throw exception

รันโปรแกรมต่อไปนี้ แล้วบันทึกผลการรัน


```cs
namespace ExceptionExample
{
    class CustomException : Exception
    {
        public CustomException(string message)
        {
        }
    }
    internal class Program
    {
        static void Main(string[] args)
        {
            try
            {
                throw new CustomException("Custom exception in TestThrow()");
            }
            catch (CustomException ex)
            {
                Console.WriteLine(ex);
            }
        }
    }
}
```
![image](https://user-images.githubusercontent.com/115066298/236689144-a99ceafe-cae8-4e46-bb97-77a9c5adb849.png)

## 15.2.2 Throw exception

รันโปรแกรมต่อไปนี้ แล้วบันทึกผลการรัน

```cs
using System;
using System.IO;

namespace Exceptions
{
    public class CatchOrder
    {
        public static void Main()
        {
            try
            {
                using (var sw = new StreamWriter("./test.txt"))
                {
                    sw.WriteLine("Hello");
                }
                using (var sr = new StreamReader("./test.txt"))
                {
                    Console.WriteLine(sr.ReadLine());
                }
                using (var sr = new StreamReader("./test1.txt"))
                {
                    Console.WriteLine(sr.ReadLine());
                }
            }
            // Put the more specific exceptions first.
            catch (DirectoryNotFoundException ex)
            {
                Console.WriteLine(ex);
            }
            catch (FileNotFoundException ex)
            {
                Console.WriteLine(ex);
            }
            // Put the least specific exception last.
            catch (IOException ex)
            {
                Console.WriteLine(ex);
            }
            Console.WriteLine("Done");
        }
    }
}
```
![image](https://user-images.githubusercontent.com/115066298/236689158-543a3e12-31d2-41a5-8da6-1b0ce1cc023c.png)
