# 15.1 Exception

ในการพัฒนาโปรแกรม จะมี error เกิดขึ้นได้ 2 แบบ
1. Compilation error
   - การผิดพลาดลักษณะนี้ Compiler จะแจ้งเตือน 
2. Run time error
   - การผิดพลาดลักษณะนี้ Compiler จะไม่แจ้งเตือน
   - จะเกิดการ crashes ของโปรแกรมขณะรัน 
   - การ crashes ของโปรแกรมเรียกว่าเกิด Exception

- Exceptions จะเกิดเมื่อโปรแกรมของเราทำงานผิดพลาด 
   - พยายามแปลง invalid string
   - พยายามเข้าถึงสมาชิกอาเรย์ที่อยู่นอกขอบเขต
   - พยายามใช้งานตัวแปร reference ที่เป็น null 
   - …และอีกหลายความพยายาม…
- ภาษา C# มีกลไกรองรับ เพื่อตรวจจับ exceptions ต่างๆ


## 15.1.1 ตัวอย่าง exception 1

รันโปรแกรมต่อไปนี้ แล้วบันทึกผลการรัน

```cs
namespace ExceptionExample
{
    internal class Program
    {
        static void Main(string[] args)
        {
            int i;
            i = int.Parse("10");
            Console.WriteLine($"i = {i}");
            int j;
            j = int.Parse("Ten");
            Console.WriteLine($"j = {j}");
        }
    }
}
```
![image](https://github.com/Prangpanwat/Week-15/assets/116150897/da381952-56f6-4793-9fa7-d9537046f258)

## 15.1.2 ตัวอย่าง exception 2

รันโปรแกรมต่อไปนี้ แล้วบันทึกผลการรัน

```cs
namespace ExceptionExample
{
    internal class Program
    {
        static void Main(string[] args)
        {
            int i;
            i = int.Parse("10");
            Console.WriteLine($"i = {i}");

            int j;
            try
            {
                j = int.Parse("Ten");
                Console.WriteLine($"j = {j}");
            }
            catch
            {
                Console.WriteLine("Invalid number.");
            }
        }
    }
}
```
![image](https://github.com/Prangpanwat/Week-15/assets/116150897/2932de80-266a-4394-bbc3-5c85670c2237)


## 15.1.3 Catching exception

รันโปรแกรมต่อไปนี้ แล้วบันทึกผลการรัน


```cs
namespace ExceptionExample
{
    internal class Program
    {
        static void Main(string[] args)
        {
            int i;
            i = int.Parse("10");
            Console.WriteLine($"i = {i}");

            int j;
            try
            {
                j = int.Parse("Ten");
                Console.WriteLine($"j = {j}");
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
                Console.WriteLine(e.StackTrace);
            }
        }
    }
}
```
![image](https://github.com/Prangpanwat/Week-15/assets/116150897/3d83cfb1-f010-497f-855c-06a987dc87df)


## 15.1.4 Try-catch-finally

- บางครั้ง เราอาจต้องการให้โปรแกรมเราทำงานอย่างปกติไม่ว่าจะมี exception เกิดขึ้นหรือไม่
   - การเชื่อมต่อ network ไม่สำเร็จ ต้องทำการยกเลิกการเชื่อมต่อ
   - การเปิดไฟล์แล้วเขียนไม่สำเร็จ ต้องปิดไฟล์นั้น
   - ฯลฯ
- โครงสร้าง try-catch จะมี finally ไว้ให้ทำในสิ่งที่เราต้องการ
- คำสั่งใน finally จะถูกเรียกเสมอ ไม่ว่าจะเกิด exception หรือไม่

รันโปรแกรมต่อไปนี้ แล้วบันทึกผลการรัน


``` cs
namespace ExceptionExample
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("--- input string = \"10\" ---");
            int i;
            try
            {
                i = int.Parse("10");
                Console.WriteLine($"i = {i}");
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                Console.WriteLine(e.StackTrace);
            }
            finally
            {
                Console.WriteLine("Normal routine operation");
            }

            Console.WriteLine("--- input string = \"Ten\" ---");
            int j;
            try
            {
                j = int.Parse("Ten");
                Console.WriteLine($"j = {j}");
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
                Console.WriteLine(e.StackTrace);
            }
            finally 
            {
                Console.WriteLine("Normal routine operation");
            }
            Console.WriteLine("--- End Program ---");
        }
    }
}
```
![image](https://github.com/Prangpanwat/Week-15/assets/116150897/70d95e87-1554-47d9-bc1a-fed996c1fe69)




