# 15.1 Exception

ในการพัฒนาโปรแกรม จะมี error เกิดขึ้นได้ 2 แบบ
1. Compilation error
   - การผิดพลาดลักษณะนี้ Compiler จะแจ้งเตือน 
2. Run time error
   - การผิดพลาดลักษณะนี้ Compiler จะไม่แจ้งเตือน
   - จะเกิดการ crashes ของโปรแกรมขณะรัน 
   - การ crashes ของโปรแกรมเรียกว่าเกิด Exception

- Exceptions จะเกิดเมื่อโปรแกรมของเราทำงานผิดพลาด 
   - พยายามแปลง invalid string
   - พยายามเข้าถึงสมาชิกอาเรย์ที่อยู่นอกขอบเขต
   - พยายามใช้งานตัวแปร reference ที่เป็น null 
   - …และอีกหลายความพยายาม…
- ภาษา C# มีกลไกรองรับ เพื่อตรวจจับ exceptions ต่างๆ


## 15.1.1 ตัวอย่าง exception 1

รันโปรแกรมต่อไปนี้ แล้วบันทึกผลการรัน

```cs
namespace ExceptionExample
{
    internal class Program
    {
        static void Main(string[] args)
        {
            int i;
            i = int.Parse("10");
            Console.WriteLine($"i = {i}");
            int j;
            j = int.Parse("Ten");
            Console.WriteLine($"j = {j}");
        }
    }
}
```
![ภาพ](https://github.com/Sittinon-Sawatdemongkol/Week-15/assets/115066278/54e35971-71f4-4310-8ad9-29a71d557149)

## 15.1.2 ตัวอย่าง exception 2

รันโปรแกรมต่อไปนี้ แล้วบันทึกผลการรัน

```cs
namespace ExceptionExample
{
    internal class Program
    {
        static void Main(string[] args)
        {
            int i;
            i = int.Parse("10");
            Console.WriteLine($"i = {i}");

            int j;
            try
            {
                j = int.Parse("Ten");
                Console.WriteLine($"j = {j}");
            }
            catch
            {
                Console.WriteLine("Invalid number.");
            }
        }
    }
}
```

![ภาพ](https://github.com/Sittinon-Sawatdemongkol/Week-15/assets/115066278/02873c9f-5a1f-4ada-9548-930f7590cd9f)

## 15.1.3 Catching exception

รันโปรแกรมต่อไปนี้ แล้วบันทึกผลการรัน


```cs
namespace ExceptionExample
{
    internal class Program
    {
        static void Main(string[] args)
        {
            int i;
            i = int.Parse("10");
            Console.WriteLine($"i = {i}");

            int j;
            try
            {
                j = int.Parse("Ten");
                Console.WriteLine($"j = {j}");
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
                Console.WriteLine(e.StackTrace);
            }
        }
    }
}
```
![ภาพ](https://github.com/Sittinon-Sawatdemongkol/Week-15/assets/115066278/03bc53ee-8ef3-4fe6-9945-8db57d0b95f6)


## 15.1.4 Try-catch-finally

- บางครั้ง เราอาจต้องการให้โปรแกรมเราทำงานอย่างปกติไม่ว่าจะมี exception เกิดขึ้นหรือไม่
   - การเชื่อมต่อ network ไม่สำเร็จ ต้องทำการยกเลิกการเชื่อมต่อ
   - การเปิดไฟล์แล้วเขียนไม่สำเร็จ ต้องปิดไฟล์นั้น
   - ฯลฯ
- โครงสร้าง try-catch จะมี finally ไว้ให้ทำในสิ่งที่เราต้องการ
- คำสั่งใน finally จะถูกเรียกเสมอ ไม่ว่าจะเกิด exception หรือไม่

รันโปรแกรมต่อไปนี้ แล้วบันทึกผลการรัน


``` cs
namespace ExceptionExample
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("--- input string = \"10\" ---");
            int i;
            try
            {
                i = int.Parse("10");
                Console.WriteLine($"i = {i}");
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                Console.WriteLine(e.StackTrace);
            }
            finally
            {
                Console.WriteLine("Normal routine operation");
            }

            Console.WriteLine("--- input string = \"Ten\" ---");
            int j;
            try
            {
                j = int.Parse("Ten");
                Console.WriteLine($"j = {j}");
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
                Console.WriteLine(e.StackTrace);
            }
            finally 
            {
                Console.WriteLine("Normal routine operation");
            }
            Console.WriteLine("--- End Program ---");
        }
    }
}
```
![ภาพ](https://github.com/Sittinon-Sawatdemongkol/Week-15/assets/115066278/1d4a2651-7b94-4481-9989-d43db92f3418)




