# 15.1 Exception

ในการพัฒนาโปรแกรม จะมี error เกิดขึ้นได้ 2 แบบ
1. Compilation error
   - การผิดพลาดลักษณะนี้ Compiler จะแจ้งเตือน 
2. Run time error
   - การผิดพลาดลักษณะนี้ Compiler จะไม่แจ้งเตือน
   - จะเกิดการ crashes ของโปรแกรมขณะรัน 
   - การ crashes ของโปรแกรมเรียกว่าเกิด Exception

- Exceptions จะเกิดเมื่อโปรแกรมของเราทำงานผิดพลาด 
   - พยายามแปลง invalid string
   - พยายามเข้าถึงสมาชิกอาเรย์ที่อยู่นอกขอบเขต
   - พยายามใช้งานตัวแปร reference ที่เป็น null 
   - …และอีกหลายความพยายาม…
- ภาษา C# มีกลไกรองรับ เพื่อตรวจจับ exceptions ต่างๆ


## 15.1.1 ตัวอย่าง exception 1

รันโปรแกรมต่อไปนี้ แล้วบันทึกผลการรัน

```cs
namespace ExceptionExample
{
    internal class Program
    {
        static void Main(string[] args)
        {
            int i;
            i = int.Parse("10");
            Console.WriteLine($"i = {i}");
            int j;
            j = int.Parse("Ten");
            Console.WriteLine($"j = {j}");
        }
    }
}
```
![image](https://github.com/suwithirunrat/Week-15/assets/116150760/74b42c3c-360c-42be-9111-e75d7626f132)

## 15.1.2 ตัวอย่าง exception 2

รันโปรแกรมต่อไปนี้ แล้วบันทึกผลการรัน

```cs
namespace ExceptionExample
{
    internal class Program
    {
        static void Main(string[] args)
        {
            int i;
            i = int.Parse("10");
            Console.WriteLine($"i = {i}");

            int j;
            try
            {
                j = int.Parse("Ten");
                Console.WriteLine($"j = {j}");
            }
            catch
            {
                Console.WriteLine("Invalid number.");
            }
        }
    }
}
```
![image](https://github.com/suwithirunrat/Week-15/assets/116150760/32a225ac-ff72-4c7d-b0a7-99bd5c1d3545)


## 15.1.3 Catching exception

รันโปรแกรมต่อไปนี้ แล้วบันทึกผลการรัน


```cs
namespace ExceptionExample
{
    internal class Program
    {
        static void Main(string[] args)
        {
            int i;
            i = int.Parse("10");
            Console.WriteLine($"i = {i}");

            int j;
            try
            {
                j = int.Parse("Ten");
                Console.WriteLine($"j = {j}");
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
                Console.WriteLine(e.StackTrace);
            }
        }
    }
}
```
![image](https://github.com/suwithirunrat/Week-15/assets/116150760/c5892b15-8a13-4cce-8242-592ffc9af9d8)


## 15.1.4 Try-catch-finally

- บางครั้ง เราอาจต้องการให้โปรแกรมเราทำงานอย่างปกติไม่ว่าจะมี exception เกิดขึ้นหรือไม่
   - การเชื่อมต่อ network ไม่สำเร็จ ต้องทำการยกเลิกการเชื่อมต่อ
   - การเปิดไฟล์แล้วเขียนไม่สำเร็จ ต้องปิดไฟล์นั้น
   - ฯลฯ
- โครงสร้าง try-catch จะมี finally ไว้ให้ทำในสิ่งที่เราต้องการ
- คำสั่งใน finally จะถูกเรียกเสมอ ไม่ว่าจะเกิด exception หรือไม่

รันโปรแกรมต่อไปนี้ แล้วบันทึกผลการรัน


``` cs
namespace ExceptionExample
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("--- input string = \"10\" ---");
            int i;
            try
            {
                i = int.Parse("10");
                Console.WriteLine($"i = {i}");
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                Console.WriteLine(e.StackTrace);
            }
            finally
            {
                Console.WriteLine("Normal routine operation");
            }

            Console.WriteLine("--- input string = \"Ten\" ---");
            int j;
            try
            {
                j = int.Parse("Ten");
                Console.WriteLine($"j = {j}");
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
                Console.WriteLine(e.StackTrace);
            }
            finally 
            {
                Console.WriteLine("Normal routine operation");
            }
            Console.WriteLine("--- End Program ---");
        }
    }
}
```
![image](https://github.com/suwithirunrat/Week-15/assets/116150760/232fc8fc-d732-450a-8899-69f363934b7b)




