# 15.2 Exception

## 15.2.1 Throw exception

รันโปรแกรมต่อไปนี้ แล้วบันทึกผลการรัน


```cs
namespace ExceptionExample
{
    class CustomException : Exception
    {
        public CustomException(string message)
        {
        }
    }
    internal class Program
    {
        static void Main(string[] args)
        {
            try
            {
                throw new CustomException("Custom exception in TestThrow()");
            }
            catch (CustomException ex)
            {
                Console.WriteLine(ex);
            }
        }
    }
}
```
![image](https://user-images.githubusercontent.com/103983336/236633172-c6716175-626c-49d2-8b21-7542201c432c.png)

## 15.2.2 Throw exception

รันโปรแกรมต่อไปนี้ แล้วบันทึกผลการรัน

```cs
using System;
using System.IO;

namespace Exceptions
{
    public class CatchOrder
    {
        public static void Main()
        {
            try
            {
                using (var sw = new StreamWriter("./test.txt"))
                {
                    sw.WriteLine("Hello");
                }
                using (var sr = new StreamReader("./test.txt"))
                {
                    Console.WriteLine(sr.ReadLine());
                }
                using (var sr = new StreamReader("./test1.txt"))
                {
                    Console.WriteLine(sr.ReadLine());
                }
            }
            // Put the more specific exceptions first.
            catch (DirectoryNotFoundException ex)
            {
                Console.WriteLine(ex);
            }
            catch (FileNotFoundException ex)
            {
                Console.WriteLine(ex);
            }
            // Put the least specific exception last.
            catch (IOException ex)
            {
                Console.WriteLine(ex);
            }
            Console.WriteLine("Done");
        }
    }
}
```
![image](https://user-images.githubusercontent.com/103983336/236633194-a7b9130f-8154-476e-b4f1-d4f54a6d552a.png)
