# 15.2 Exception

## 15.2.1 Throw exception

รันโปรแกรมต่อไปนี้ แล้วบันทึกผลการรัน


```cs
namespace ExceptionExample
{
    class CustomException : Exception
    {
        public CustomException(string message)
        {
        }
    }
    internal class Program
    {
        static void Main(string[] args)
        {
            try
            {
                throw new CustomException("Custom exception in TestThrow()");
            }
            catch (CustomException ex)
            {
                Console.WriteLine(ex);
            }
        }
    }
}
```
![image](https://github.com/tnpn2545/Week-15/assets/115066414/650c6a28-28bf-4983-b0bb-33d86b1e6b4f)

## 15.2.2 Throw exception

รันโปรแกรมต่อไปนี้ แล้วบันทึกผลการรัน

```cs
using System;
using System.IO;

namespace Exceptions
{
    public class CatchOrder
    {
        public static void Main()
        {
            try
            {
                using (var sw = new StreamWriter("./test.txt"))
                {
                    sw.WriteLine("Hello");
                }
                using (var sr = new StreamReader("./test.txt"))
                {
                    Console.WriteLine(sr.ReadLine());
                }
                using (var sr = new StreamReader("./test1.txt"))
                {
                    Console.WriteLine(sr.ReadLine());
                }
            }
            // Put the more specific exceptions first.
            catch (DirectoryNotFoundException ex)
            {
                Console.WriteLine(ex);
            }
            catch (FileNotFoundException ex)
            {
                Console.WriteLine(ex);
            }
            // Put the least specific exception last.
            catch (IOException ex)
            {
                Console.WriteLine(ex);
            }
            Console.WriteLine("Done");
        }
    }
}
```
![image](https://github.com/tnpn2545/Week-15/assets/115066414/827af449-1c7a-4223-90e9-61d479c20496)
